### PR TITLE
Add stm32 low level drivers

### PR DESCRIPTION
**Pull request by rahmanih**

### CODE REVIEW

**Comment by rahmanih** [comment]
Hi @wickste,

Woud you please review this PR and merge if it is O.K.?

regards
Haithem.

**Comment by ayedm1** [comment]
Hi @rahmanih ,

I suggest to 

1. add stm32_drivers under fx_drivers folder which regroup other semi-vendor delivred fx drivers 

common
|_ fx_drivers
   |_ stm32
   |_ nxp...
   |_ ............ 

2. add a readme file to guide users start from this files, what to modify to avoid compilation error.
       (for example  #include "stm32XXXX.h" --> #include "stm32h7xx.h")

**Comment by rahmanih** [comment]
Hi @wickste,

Could you review this PR please?

regards
Haithem.

**Comment by wickste** [comment]
Thank you @rahmanih - this looks good!

I will need to hold off on merging it for the moment as we are still finalizing the new development process. We need to make sure all new contributions are compliant with that process, so we can continue to obtains safety certification for this code base.

**Pull request closed without merging**
